services:

  web:
    ports:
      - "${PORT_WEB_HOST}:${PORT_WEB_CONTAINER}"
    volumes:
      - ${VOLUME_WEB}:/var/www/html
    build:
      context: ./web
      args:
        - XDEBUG=${XDEBUG}
        - PHP_IMAGE_TAG=${PHP_IMAGE_TAG}

  db:
    image: mariadb:10.11.7
    volumes:
      - ${VOLUME_DB}:/var/lib/mysql:Z
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}

  adminer:
    image: adminer
    ports:
      - ${PORT_ADMINER}:8080
